## Write a Numpy program to compute the multiplication of two given matrixes

In [3]:
import numpy as np

In [4]:
matrix1=np.array([[1,2,3],
               [4,5,6]])

matrix2=np.array([[1,0,3],
               [0,2,0]])
#operation
print(matrix1 * matrix2)

[[ 1  0  9]
 [ 0 10  0]]


## Write a NumPy program to compute the determinant of a given square array

In [5]:
array = np.array([[1,2],
               [3,4]])
result=np.linalg.det(array)
result

-2.0000000000000004

## Write a NumPy program to compute the cross product of two given vectors

In [6]:
v1=np.array([1,2,3])
v2=np.array([3,4,5])
print(v1.dot(v2))

26


## Write a NumPy program to compute the condition number of a given matrix

In [8]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

cond_num = np.linalg.cond(A)

print("The condition number of the matrix A is:", cond_num)

The condition number of the matrix A is: 3.813147060626918e+16


## Write a NumPy program to compute the inverse of a given matrix

In [12]:
martix=np.array([
    [1,2],
    [3,4]

])

In [13]:
result=np.linalg.inv(martix)

In [14]:
result

array([[-2. ,  1. ],
       [ 1.5, -0.5]])